import "server-only";
import { z } from "zod";
import type { SettingEntry } from "./registry";

export const CATALOG: readonly SettingEntry[] = [
  // --- security (envSecret) ---
  {
    kind: "envSecret",
    key: "secret.database",
    category: "security",
    group: "security",
    groupOrder: 1,
    order: 10,
    title: "데이터베이스 연결",
    description: "PostgreSQL 연결 문자열(런타임 secret).",
    permission: { resource: "admin.settings", action: "view" },
    envVars: [{ name: "DATABASE_URL", kind: "value" }],
  },
  {
    kind: "envSecret",
    key: "secret.auth",
    category: "security",
    group: "security",
    groupOrder: 2,
    order: 11,
    title: "인증 secret",
    description: "NextAuth 세션 서명 secret(NEXTAUTH_SECRET 또는 AUTH_SECRET).",
    permission: { resource: "admin.settings", action: "view" },
    envVars: [{ name: "NEXTAUTH_SECRET", kind: "value", aliases: ["AUTH_SECRET"] }],
  },
  // --- integrations (envSecret) ---
  {
    kind: "envSecret",
    key: "secret.google",
    category: "integrations",
    group: "google",
    groupOrder: 1,
    order: 20,
    title: "Google 서비스 계정",
    description: "Google API 서비스 계정 키 파일.",
    permission: { resource: "integrations.google", action: "view" },
    envVars: [{ name: "GOOGLE_APPLICATION_CREDENTIALS", kind: "filePath" }],
  },
  {
    kind: "envSecret",
    key: "secret.smtp",
    category: "integrations",
    group: "mail",
    groupOrder: 1,
    order: 21,
    title: "SMTP 비밀번호",
    description: "메일 발송 SMTP 계정 비밀번호.",
    permission: { resource: "integrations.smtp", action: "view" },
    envVars: [{ name: "SMTP_PASSWORD", kind: "value" }],
  },
  {
    kind: "envSecret",
    key: "secret.libreoffice",
    category: "integrations",
    group: "documents",
    groupOrder: 1,
    order: 22,
    title: "LibreOffice 경로",
    description: "PDF 변환용 LibreOffice 실행 파일 경로.",
    permission: { resource: "integrations.templates", action: "view" },
    envVars: [{ name: "LIBREOFFICE_PATH", kind: "filePath" }],
  },
  // --- integrations (systemSetting) ---
  // NOTE: integrations.smtp.host·port 는 제거됨(env 전용 — host=F4, port=P3/A2). host/user/secure/port/password는 env 신뢰경계 유지.
  //        DB 편집 가능한 SMTP 필드 = fromAddress 하나뿐.
  {
    kind: "systemSetting",
    key: "integrations.smtp.fromAddress",
    category: "integrations",
    group: "mail",
    groupOrder: 2,
    order: 32,
    title: "발신 주소",
    description: "메일 기본 발신 이메일 주소.",
    permission: { resource: "integrations.smtp", action: "configure" },
    schema: z.string().email().or(z.literal("")), // 빈 문자열="미설정" 허용, 그 외엔 이메일 형식
    default: "",
    audit: "summary",
    fallbackSafe: false,
  },
  {
    kind: "systemSetting",
    key: "integrations.google.calendarIds",
    category: "integrations",
    group: "google",
    groupOrder: 2,
    order: 33,
    title: "Google 캘린더 목록",
    description: "동기화 대상 Google 캘린더 ID 목록.",
    permission: { resource: "integrations.google", action: "configure" },
    schema: z.array(z.string().min(1)),
    default: [],
    audit: "summary",
    fallbackSafe: false,
  },
  // --- workflows ---
  {
    kind: "relational",
    key: "workflows.mail.recipients",
    category: "workflows",
    group: "workflows",
    groupOrder: 1,
    order: 40,
    title: "메일 수신자",
    description: "주소록과 업무유형×발송단계별 기본 수신자 세트를 관리합니다.",
    permission: { resource: "workflows.mail", action: "configure" },
    model: "MailContact",
    manageHref: "/admin/settings/mail-recipients",
  },
  {
    kind: "relational",
    key: "workflows.billing.config",
    category: "workflows",
    group: "workflows",
    groupOrder: 2,
    order: 41,
    title: "대금청구 설정",
    description: "연도별 계약·청구 설정(전용 화면에서 관리, Phase 4).",
    permission: { resource: "workflows.billing", action: "configure" },
    model: "BillingConfig",
    manageHref: "/workflows/billing/settings",
  },
  // --- leave (systemSetting) ---
  {
    kind: "systemSetting",
    key: "leave.notifications.onRequest",
    category: "leave",
    group: "leave",
    groupOrder: 1,
    order: 50,
    title: "연차 신청 알림 메일",
    description: "직원이 연차를 신청하면 승인 권한자에게 알림 메일을 보냅니다.",
    permission: { resource: "leave.admin", action: "configure" },
    schema: z.boolean(),
    default: true,
    audit: "full",
    fallbackSafe: true,
  },
  {
    kind: "systemSetting",
    key: "leave.notifications.onApprove",
    category: "leave",
    group: "leave",
    groupOrder: 2,
    order: 51,
    title: "연차 승인 알림 메일",
    description: "연차가 승인되면 신청자 본인에게 알림 메일을 보냅니다.",
    permission: { resource: "leave.admin", action: "configure" },
    schema: z.boolean(),
    default: true,
    audit: "full",
    fallbackSafe: true,
  },
  {
    kind: "systemSetting",
    key: "leave.notifications.onReject",
    category: "leave",
    group: "leave",
    groupOrder: 3,
    order: 52,
    title: "연차 반려 알림 메일",
    description: "연차가 반려되면 신청자 본인에게 알림 메일을 보냅니다.",
    permission: { resource: "leave.admin", action: "configure" },
    schema: z.boolean(),
    default: true,
    audit: "full",
    fallbackSafe: true,
  },
];

export const SYSTEM_KEYS: ReadonlySet<string> = new Set(
  CATALOG.filter((e) => e.kind === "systemSetting").map((e) => e.key),
);

export function getEntry(key: string): SettingEntry | undefined {
  return CATALOG.find((e) => e.key === key);
}
